

replicaCount: 1

image: 
  repository: gal355/go-web-app
  pullPolicy: IfNotPresent
  tag: "21497377378"

ingress:
  enabled: false
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific