apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
    - protocol: TCP
      port: 80          # הפורט של הסרוויס
      targetPort: 8080  # הפורט של הקונטיינר (השלוחה הפנימית)
      nodePort: 30001   # הפורט שדרכו תיכנסי מהדפדפן (localhost:30001)